/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Database: typeof import('./src/components/Database.vue')['default']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Generate: typeof import('./src/components/Generate.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Project: typeof import('./src/components/Project.vue')['default']
    Template: typeof import('./src/components/Template.vue')['default']
  }
}
